FROM python:3.10-slim

ENV PYTHONDONTWRITEBYTECODE=1 \
    PYTHONUNBUFFERED=1 \
    PIP_NO_CACHE_DIR=1

WORKDIR /app

COPY requirements/front.txt .
RUN pip install --no-cache-dir -r front.txt

COPY frontend ./frontend

EXPOSE 7860

CMD ["python", "-m", "frontend.app"]